apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    uid: influx
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      httpMode: POST
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: true
    editable: false
